spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
server:
  port: 8788

# routes to serviceId 这里边是通过serviceid来绑定地址，当在路径后添加/api-a/   则是访问EUREKA-CLIENT对应的服务。
zuul:
  routes: #zuul 会缓存请求 当某一服务断开后，要过一段时间才会切换到另一服务
    api-a: #此处随便定义
      path: /api-a/**
      serviceId: EUREKA-CLIENT #对应Eureka中的服务名
    api-a-url: # routes to url  这里是绑定具体的ip地址
      path: /api-a-url/**  #所有/api-a-url/**请求都会映射到http://localhost:8761/上
      url: http://localhost:8761/
  host:  #Zuul中默认就已经集成了Ribbon负载均衡和Hystix熔断机制 Hystrix 默认时间较短 容易造成ZuulException
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

 #eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/